package:
  name: veoibd-synapse-data-manager
  version: "0.0.1"

source:
  path: ../

#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - "veoibd_synapse=veoibd_synapse.cli.cli:cli"

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - click



  run:
    - python
    - click



test:
  # Python imports
  imports:
      - veoibd_synapse

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - veoibd_synapse --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ScottSnapperLab/veoibd-synapse-data-manager
  license: MIT
  summary: 'Admin related logistics regarding uploading and annotating data to Synapse for members of the VEOIBD consortium.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
