processManagement:
   fork: true
net:
   bindIp: 127.0.0.1
   port: 27017
systemLog:
   destination: file
   path: "data/mongodb/logs/mongod.log"
   logAppend: true
   quiet: false
storage:
   dbPath: "data/mongodb/db"
   journal:
      enabled: true
security:
   authorization: disabled