SITE_NAME: Site Name

INSTITUTION: Institution Name

PI:
    FIRST_NAME: First
    LAST_NAME: Last
    EMAIL: user@dom.com

DATA_LIAISON:
    FIRST_NAME: First
    LAST_NAME: Last
    EMAIL: user@dom.com    
